development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: booking_dev
  username: root
  password: root
  pool: 5
  host: localhost

production:
  adapter:  postgresql
  database: d3kelr3mcc5mnh
  username: wktmmkrhoctwao
  password: 49ecfd93ab1d817f4799494ee139abba54fd38b3298e5a2312539ee14992206b
  pool: 5
  encoding: unicode
  host: ec2-18-206-84-251.compute-1.amazonaws.com

