# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4531545543d7368dc0b388038ae05126327d5f0b8180298d0166bcb7c13085711511cd55024db90f8e7227cff2be181e12779d0d4ae8c6a8e84d4dd89707037a

test:
  secret_key_base: dfa8126e020384826e174c3996a3828ff15d9dfb916145f8e056e92d986d0bb8a1365330d5881c9c9f8f78d325f62e54905cb03560feda7b9acbe3e3e69121f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
